# Permalinks
#
permalink: /:title

# Setup
title: "jrheard's blog"
url: http://blog.jrheard.com

baseurl: ''

# Custom vars
version: 1.0.0

assets:
  digest: true

# Build settings
markdown: kramdown
encoding: utf-8
gems:
  - jekyll-feed
