# Permalinks
#
permalink:           /:title

# Setup
title:               "jrheard's blog"
url:                 http://blog.jrheard.com

baseurl:             ''

# trying to diagnose an issue, https://jekyllrb.com/docs/upgrading/2-to-3/ recommends this
future: true

# Custom vars
version:             1.0.0

assets:
  digest: true

# Build settings
markdown: kramdown
encoding: utf-8
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
